int make(WINDOW *win1,int);
int make1(WINDOW *win_1, int m);
void print_in_middle(WINDOW *win, int starty, int startx, int width, char *string, chtype color);
int login(WINDOW *win, int m);
int designed_by(WINDOW *win_1);
int match(char* usrname, char* pass, int m);
int staffmenu(WINDOW* win);
int adminmenu(WINDOW* win);
int add_user(WINDOW *win);
int add_to_file(FORM *form, FIELD **field);
char *string(char *stf);
int del_user(WINDOW* win);
int delete_from_file(FORM *form, FIELD **field);
int add_account(WINDOW *win);
int make2(WINDOW *win_1, int m);
int add_acc_to_file(FORM *form, FIELD **field);
int check_date(char *date);
int cash_deposit(WINDOW *win);
float cash_file(FORM *form, FIELD **field, int m);
int cash_withdrawal(WINDOW *win);
float transfer_file(FORM *form, FIELD **field); 
int fund_transfer(WINDOW* win);
int delete_acc_file(FORM *form, FIELD **field);
int del_account(WINDOW* win);
int change_pass(WINDOW* win);
int change_pass_file(FORM *form, FIELD **field);
int view_acc_file(FORM *form, FIELD **field, WINDOW *win, int a);
int account_info(WINDOW* win, int a);
int display(WINDOW *win,  int m, int a);
int display1(WINDOW *win,  char *str, int a);
int user_info(WINDOW* win, int a);
int view_user_file(FORM *form, FIELD **field, WINDOW *win, int a);
int make3(WINDOW *win_1,int m, int a);
char* sys_date();
char* sys_date1();
void uptodate();

